site_name: Gemini by Example
site_url: https://shaneholloman.github.io/geminibyexample
site_description: Learn the Gemini API through annotated examples
site_author: Shane Holloman
repo_url: https://github.com/shaneholloman/geminibyexample
repo_name: shaneholloman/geminibyexample
edit_uri: edit/main/docs/

docs_dir: docs
site_dir: site

# Theme configuration
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
nav:
- Home: index.md
- Text:
  - Overview: text/index.md
  - Streaming Recipe Generation: text/mkdocs-testing.md
  - Simple text generation: text/simple-text-generation.md
  - Streaming text: text/streaming-text.md
  - System prompt: text/system-prompt.md
  - Reasoning models: text/reasoning-models.md
  - Structured output: text/structured-output.md
- Images:
  - Overview: images/index.md
  - Image question answering: images/image-question-answering.md
  - Image generation (Gemini and Imagen): images/image-generation-gemini-and-imagen.md
  - Edit an image: images/edit-an-image.md
  - Bounding boxes: images/bounding-boxes.md
  - Image segmentation: images/image-segmentation.md
- Audio:
  - Overview: audio/index.md
  - Audio question answering: audio/audio-question-answering.md
  - Audio transcription: audio/audio-transcription.md
  - Audio summarization: audio/audio-summarization.md
- Video:
  - Overview: video/index.md
  - Video question answering: video/video-question-answering.md
  - Video summarization: video/video-summarization.md
  - Video transcription: video/video-transcription.md
  - YouTube video summarization: video/youtube-video-summarization.md
- PDFs and other data types:
  - Overview: pdfs-and-other-data-types/index.md
  - PDF and CSV data analysis and summarization: pdfs-and-other-data-types/pdf-and-csv-data-analysis-and-summarization.md
  - Translate documents: pdfs-and-other-data-types/translate-documents.md
  - Extract structured data from a PDF: pdfs-and-other-data-types/extract-structured-data-from-a-pdf.md
- Agentic behaviour:
  - Overview: agentic-behaviour/index.md
  - Function calling & tool use: agentic-behaviour/function-calling-tool-use.md
  - Code execution: agentic-behaviour/code-execution.md
  - Model Context Protocol: agentic-behaviour/model-context-protocol.md
  - Grounded responses with search tool: agentic-behaviour/grounded-responses-with-search-tool.md
- Token counting & context windows:
  - Overview: token-counting-context-windows/index.md
  - Model context windows: token-counting-context-windows/model-context-windows.md
  - Counting chat tokens: token-counting-context-windows/counting-chat-tokens.md
  - Calculating multimodal input tokens: token-counting-context-windows/calculating-multimodal-input-tokens.md
  - Context caching: token-counting-context-windows/context-caching.md
- Miscellaneous:
  - Overview: miscellaneous/index.md
  - Rate limits and retries: miscellaneous/rate-limits-and-retries.md
  - Concurrent requests and generation: miscellaneous/concurrent-requests-and-generation.md
  - Embeddings generation: miscellaneous/embeddings-generation.md
  - Safety settings and filters: miscellaneous/safety-settings-and-filters.md
  - LiteLLM: miscellaneous/litellm.md
# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|\.|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
